export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT', 
    
    GETBYUSERNAMEL_REQUEST: 'USERS_GETBYUSERNAME_REQUEST',
    GETBYUSERNAME_SUCCESS: 'USERS_GETBYUSERNAME_SUCCESS',
    GETBYUSERNAME_FAILURE: 'USERS_GETBYUSERNAME_FAILURE',
};